# Qwen-Audio-Chat

Following https://huggingface.co/Qwen/Qwen-Audio-Chat

In [69]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
import torch
torch.manual_seed(1234)

In [70]:
# Note: The default behavior now has injection attack prevention off.
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-Audio-Chat", trust_remote_code=True)

# use bf16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-Audio-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
# use fp16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-Audio-Chat", device_map="auto", trust_remote_code=True, fp16=True).eval()
# use cpu only
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-Audio-Chat", device_map="cpu", trust_remote_code=True).eval()
# use cuda device
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-Audio-Chat", device_map="cuda", trust_remote_code=True).eval()

# Specify hyperparameters for generation (No need to do this if you are using transformers>4.32.0)
# model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-Audio-Chat", trust_remote_code=True)

audio_start_id: 155163, audio_end_id: 155164, audio_pad_id: 151851.

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention

Loading checkpoint shards:   0%|          | 0/9 [00:00<?, ?it/s]

## Examples

## Our data

In [3]:
query = tokenizer.from_list_format([
    {'audio': 'audio/fatalvapes_asmr_narration.mp4'}, # Either a local path or an url
    {'text': 'what does the person say?'},
])
response, history = model.chat(tokenizer, query=query, history=None)
print(response)

The person says in English: "Masking X-pan Lush Ice".

In [4]:
# 2nd dialogue turn
response, history = model.chat(tokenizer, 'Is there rhythmic tapping or noises in the background?', history=history)
print(response)

Yes, there is rhythmic tapping in the background.

In [10]:
response, history = \
    model.chat(tokenizer,
               #'Is there rhythmic tapping or non-word noises in the background? Limit your response to a single word that is the percentage probability for how certain you are.',
               'Is there rhythmic tapping or non-word noises in the background, excluding vocals or music?' +
               'Limit your response to a single word that is the percentage probability for how certain you are.',
    history = history)
print(response)

Yes, there is rhythmic tapping in the background at a probability of 80%.

In [9]:
# Compare to a non-ASMR audio sample which contains music:
query = tokenizer.from_list_format([
    {'audio': 'videos/vaping_modeling.mp4'}, # Either a local path or an url
    {'text': #'Is there rhythmic tapping or non-word noises in the background? Provide your response as a numeric probability.'
              'Is there rhythmic tapping or non-word noises in the background, ignoring vocals or music?' + 
              'Limit your response to a single word that is the percentage probability for how certain you are.'},
])
response, history = model.chat(tokenizer, query=query, history=None)
print(response)

Yes, there is rhythmic tapping in the background at a probability of 80%.

In [138]:
# See if it knows what ASMR is:
query = tokenizer.from_list_format([
    {'text': 'What is Autonomous Sensory Meridian Response (also known as ASMR)?'},
])
response, history = model.chat(tokenizer, query=query, history=None)
print(response)

Autonomous Sensory Meridian Response (ASMR) is a phenomenon characterized by a tingling or relaxing sensation that typically begins in the head and spreads to the rest of the body. It is often triggered by specific auditory or visual stimuli, such as whispering, tapping, or certain types of music. Some people report that ASMR triggers a feeling of deep relaxation and well-being, while others describe it as a more intense version of the tingling sensation they get when they're "pins and needles." The exact cause of ASMR is not yet fully understood, but it is thought to involve the activation of certain areas of the brain, such as the auditory and visual cortex.

#### Query function

In [78]:
# Compare to a non-ASMR audio sample which contains music:
def query_file(file_path, query_text, history = None):
    query = tokenizer.from_list_format([
        {'audio': file_path}, # Either a local path or an url
        {'text': query_text},
    ])
    response, history = model.chat(tokenizer, query = query, history = history)
    return(response, history)

prompt_asmr = ('Is there rhythmic tapping or non-word noises in the background, ignoring vocals or music?' + 
              'Limit your response to a single word that is the percentage probability for how certain you are, like 5% or 95%.')

response, history = query_file('videos/vaping_modeling.mp4',
           query_text = prompt_asmr)
response

'Yes, there is rhythmic tapping in the background.'

## Performance evaluation

### Import labels

In [8]:
# pip install "pandas<2.0.0"
import pandas as pd
# https://docs.google.com/spreadsheets/d/1r9IlI6dze2Okh4EQ5v1ZhGut1eTkzkc_/edit#gid=42652425
labels = pd.read_excel("audio/ASMR_data_labeled.xlsx")
labels.rename(columns = {'ASMR (yes/no)': 'is_asmr'}, inplace = True)
labels['shortcode'] = labels.videoURL.str.extract('\/([^/]+)/$')
labels['is_asmr'] = (labels.is_asmr.values == 'yes').astype(int)
labels.head()

,profile,videoURL,video_posted_date,is_asmr,shortcode
0,noniquennisa,https://www.instagram.com/reel/CnBxPwxDlG4/,2023-01-05 00:00:00,0,CnBxPwxDlG4
1,noniquennisa,https://www.instagram.com/reel/CnEWAuGjhyg/,2023-01-06 00:00:00,0,CnEWAuGjhyg
2,noniquennisa,https://www.instagram.com/reel/CnG7P4cjdmz/,2023-01-07 00:00:00,0,CnG7P4cjdmz
3,noniquennisa,https://www.instagram.com/reel/CnMEacLjnko/,2023-01-09 00:00:00,1,CnMEacLjnko
4,noniquennisa,https://www.instagram.com/reel/CnOpQ3uDtr5/,2023-01-10 00:00:00,0,CnOpQ3uDtr5

In [55]:
print(labels.isna().sum())
labels.dropna(inplace = True) # 2 blank rows
print(labels.isna().sum())

profile              2
videoURL             2
video_posted_date    2
is_asmr              0
shortcode            2
dtype: int64
profile              0
videoURL             0
video_posted_date    0
is_asmr              0
shortcode            0
dtype: int64

### Import video names

In [56]:
import pickle

# Requires pandas 1 rather than 2, per above pip line.
df = pickle.load(open("audio/vape_file_dictionary.pkl", 'rb'))
df['shortcode'] = df.web_url.str.extract('\/([^/]+)/$')
print(df.shape)
# We drop 3 rows here.
df.dropna(inplace = True)
print(df.shape)
df.head()

(477, 3)
(474, 3)

,web_url,file,shortcode
21592,https://www.instagram.com/p/C4KqjIqyt0b/,noniquennisa/reels/2024-03-06 16.49.28 3317651...,C4KqjIqyt0b
21593,https://www.instagram.com/p/C3e5J1pSAvk/,noniquennisa/reels/2024-02-18 16.49.18 3305330...,C3e5J1pSAvk
21594,https://www.instagram.com/p/C3R_pr6yeU-/,noniquennisa/reels/2024-02-13 16.36.54 3301699...,C3R_pr6yeU-
21595,https://www.instagram.com/p/C3PdlEbJiYw/,noniquennisa/reels/2024-02-12 16.59.35 3300987...,C3PdlEbJiYw
21596,https://www.instagram.com/p/C3CkwciS6-Q/,noniquennisa/reels/2024-02-07 16.56.25 3297359...,C3CkwciS6-Q

### Integrate videos and labels

In [63]:
df2 = labels.merge(df, on = "shortcode", how = 'left')
# 437 - this is correct.
print(df2.shape)
print(df2.is_asmr.value_counts())
df2.head()

(437, 7)
0    329
1    108
Name: is_asmr, dtype: int64

,profile,videoURL,video_posted_date,is_asmr,shortcode,web_url,file
0,noniquennisa,https://www.instagram.com/reel/CnBxPwxDlG4/,2023-01-05 00:00:00,0,CnBxPwxDlG4,https://www.instagram.com/p/CnBxPwxDlG4/,noniquennisa/reels/2023-01-05 17.00.12 3008902...
1,noniquennisa,https://www.instagram.com/reel/CnEWAuGjhyg/,2023-01-06 00:00:00,0,CnEWAuGjhyg,https://www.instagram.com/p/CnEWAuGjhyg/,noniquennisa/reels/2023-01-06 17.00.17 3009627...
2,noniquennisa,https://www.instagram.com/reel/CnG7P4cjdmz/,2023-01-07 00:00:00,0,CnG7P4cjdmz,https://www.instagram.com/p/CnG7P4cjdmz/,noniquennisa/reels/2023-01-07 17.03.18 3010353...
3,noniquennisa,https://www.instagram.com/reel/CnMEacLjnko/,2023-01-09 00:00:00,1,CnMEacLjnko,https://www.instagram.com/p/CnMEacLjnko/,noniquennisa/reels/2023-01-09 16.59.46 3011801...
4,noniquennisa,https://www.instagram.com/reel/CnOpQ3uDtr5/,2023-01-10 00:00:00,0,CnOpQ3uDtr5,https://www.instagram.com/p/CnOpQ3uDtr5/,noniquennisa/reels/2023-01-10 17.00.18 3012526...

In [64]:
df2.isna().sum()

profile              0
videoURL             0
video_posted_date    0
is_asmr              0
shortcode            0
web_url              3
file                 3
dtype: int64

In [65]:
# 3 labels were not scraped - can just exclude these.
print(df2[df2.web_url.isna()])
df2.dropna(inplace = True)
print(df2.isna().sum())

    profile                                     videoURL    video_posted_date  \
157  a_kidz  https://www.instagram.com/reel/Cn3cF83MVYQ/  2023-01-25 00:00:00
158  a_kidz  https://www.instagram.com/reel/CoC1t59OwHL/  2023-01-30 00:00:00
162  a_kidz  https://www.instagram.com/reel/Co7CgpwLU2E/  2023-02-21 00:00:00

     is_asmr    shortcode web_url file
157        0  Cn3cF83MVYQ     NaN  NaN
158        0  CoC1t59OwHL     NaN  NaN
162        0  Co7CgpwLU2E     NaN  NaN
profile              0
videoURL             0
video_posted_date    0
is_asmr              0
shortcode            0
web_url              0
file                 0
dtype: int64

### Find videos

In [82]:
from pathlib import Path
from pyprojroot import here

df2['found'] = 0

for i, row in df2.iterrows():
    file_str = row['file']
    file_path = Path(str("audio/" + file_str))
    if file_path.is_file():
        df2.at[i, 'found'] = 1

# Found all files.
print(df2.found.value_counts(), '\n')
print(df2[['profile', 'found']].groupby(['profile', 'found']).value_counts())
# No longer any missing files.
# [missing_files[i] for i in list(missing_files.keys())[:10]]

1    434
Name: found, dtype: int64

profile       found
a_kidz        1        153
fatal_vapes   1        129
noniquennisa  1        152
dtype: int64

## Prompt variations

In [134]:
# Version 1 (2024-05-30):
# AUC: 0.56
prompt_asmr = ('Is there rhythmic tapping or non-word noises in the background, ignoring vocals or music?' + 
              'Limit your response to a single word that is the percentage probability for how certain you are, like 5% or 95%.')

# Version 2 (2024-05-31):
# AUC: 0.40
prompt_asmr = ('Is there rhythmic tapping like the Autonomous Sensory Meridian Response (also known as ASMR)? ' + 
               'It may sound like tapping on a packaging box. This should exclude vocals or music. ' +
               'Limit your response to a single word that is the percentage probability for how certain you are, like 5% or 95%.')

### Analyze videos

In [135]:
# Reset results
df2['response'] = ''
df2['successes'] = 0
df2['attempts'] = 0

In [136]:
%%time

import math, re
min_successes = 3
max_tries = 10
for i, row in df2.iterrows():
    # Allow hotstarting.
    if row['response'] != '':
        continue
    file_path = str("audio/" + row['file'])
    attempts = 0
    successes = 0
    probs = []
    responses = []
    while attempts < max_tries and successes < min_successes:
        # Run and parse simultaneously
        response, _ = query_file(file_path,
               query_text = prompt_asmr)
        responses.append(response)
        # Extract the probabily if included in the response.
        result = re.search('(\d+)%', response)
        if result:
            prob = float(result.group(1)) / 100
            if not math.isnan(prob):
                probs.append(prob)
                successes = successes + 1
        attempts = attempts + 1

    df2.at[i, 'response'] = responses
    df2.at[i, 'pred_asmr'] = np.mean(probs)
    df2.at[i, 'attempts'] = attempts
    df2.at[i, 'successes'] = successes
    print("Completed", i, "with", attempts, "attempts and", successes, f"successes. Prob = {np.mean(probs):0.3f}", "Actual:", row['is_asmr'])

Completed 0 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 1 with 6 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 2 with 5 attempts and 3 successes. Prob = 0.783 Actual: 0
Completed 3 with 7 attempts and 3 successes. Prob = 0.767 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 4 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 5 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 6 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 7 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 8 with 5 attempts and 3 successes. Prob = 0.567 Actual: 0
Completed 9 with 10 attempts and 2 successes. Prob = 0.050 Actual: 1
Completed 10 with 7 attempts and 3 successes. Prob = 0.350 Actual: 1
Completed 11 with 10 attempts and 2 successes. Prob = 0.500 Actual: 0
Completed 12 with 10 attempts and 3 successes. Prob = 0.733 Actual: 0
Completed 13 with 5 attempts and 3 successes. Prob = 0.550 Actual: 0
Completed 14 with 3 attempts and 3 successes. Prob = 0.517 Actual: 0
Completed 15 with 10 attempts and 2 successes. Prob = 0.875 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 16 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 17 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 18 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 19 with 6 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 20 with 3 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 21 with 10 attempts and 2 successes. Prob = 0.500 Actual: 0
Completed 22 with 9 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 23 with 3 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 24 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 25 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 26 with 10 attempts and 2 successes. Prob = 0.425 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 27 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 28 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 29 with 10 attempts and 2 successes. Prob = 0.875 Actual: 0
Completed 30 with 10 attempts and 3 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 31 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 32 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 33 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 34 with 10 attempts and 2 successes. Prob = 0.500 Actual: 0
Completed 35 with 9 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 36 with 3 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 37 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 38 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 39 with 10 attempts and 2 successes. Prob = 0.500 Actual: 0
Completed 40 with 10 attempts and 2 successes. Prob = 0.050 Actual: 0
Completed 41 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 42 with 4 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 43 with 10 attempts and 2 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 44 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 45 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 46 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 47 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 48 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 49 with 10 attempts and 2 successes. Prob = 0.875 Actual: 0
Completed 50 with 4 attempts and 3 successes. Prob = 0.583 Actual: 0
Completed 51 with 10 attempts and 2 successes. Prob = 0.500 Actual: 0
Completed 52 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0
Completed 53 with 6 attempts and 3 successes. Prob = 0.350 Actual: 1
Completed 54 with 4 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 55 with 10 attempts and 2 successes. Prob = 0.425 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 56 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 57 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 58 with 3 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 59 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 60 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 61 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 62 with 10 attempts and 2 successes. Prob = 0.425 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 63 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 64 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 65 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 66 with 4 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 67 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 68 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 69 with 4 attempts and 3 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 70 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 71 with 5 attempts and 3 successes. Prob = 0.287 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 72 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 73 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 74 with 6 attempts and 3 successes. Prob = 0.300 Actual: 0
Completed 75 with 4 attempts and 3 successes. Prob = 0.650 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 76 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 77 with 10 attempts and 2 successes. Prob = 0.825 Actual: 0
Completed 78 with 9 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 79 with 3 attempts and 3 successes. Prob = 0.650 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 80 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 81 with 10 attempts and 1 successes. Prob = 0.950 Actual: 1
Completed 82 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1
Completed 83 with 9 attempts and 3 successes. Prob = 0.650 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 84 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 85 with 4 attempts and 3 successes. Prob = 0.017 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 86 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 87 with 5 attempts and 3 successes. Prob = 0.267 Actual: 0
Completed 88 with 4 attempts and 3 successes. Prob = 0.900 Actual: 0
Completed 89 with 8 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 90 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 91 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 92 with 3 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 93 with 10 attempts and 2 successes. Prob = 0.475 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 94 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 95 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 96 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 97 with 10 attempts and 3 successes. Prob = 0.050 Actual: 1
Completed 98 with 3 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 99 with 10 attempts and 1 successes. Prob = 0.950 Actual: 1
Completed 100 with 3 attempts and 3 successes. Prob = 0.337 Actual: 0
Completed 101 with 3 attempts and 3 successes. Prob = 0.800 Actual: 0
Completed 102 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 103 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 104 with 10 attempts and 2 successes. Prob = 0.500 Actual: 1
Completed 105 with 5 attempts and 3 successes. Prob = 0.583 Actual: 0
Completed 106 with 10 attempts and 2 successes. Prob = 0.500 Actual: 1
Completed 107 with 10 attempts and 1 successes. Prob = 0.700 Actual: 1
Completed 108 with 4 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 109 with 10 attempts and 2 successes. Prob = 0.875 Actual: 1
Completed 110 with 7 attempts and 3 successes. Prob = 0.300 Actual: 1
Completed 111 with 10 attempts and 2 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 112 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 113 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 114 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 115 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 116 with 10 attempts and 3 successes. Prob = 0.050 Actual: 1
Completed 117 with 10 attempts and 1 successes. Prob = 0.000 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 118 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 119 with 3 attempts and 3 successes. Prob = 0.337 Actual: 0
Completed 120 with 4 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 121 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1
Completed 122 with 3 attempts and 3 successes. Prob = 0.833 Actual: 0
Completed 123 with 8 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 124 with 8 attempts and 3 successes. Prob = 0.583 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 125 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 126 with 5 attempts and 3 successes. Prob = 0.850 Actual: 1
Completed 127 with 10 attempts and 2 successes. Prob = 0.500 Actual: 1
Completed 128 with 5 attempts and 3 successes. Prob = 0.600 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 129 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 130 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1
Completed 131 with 10 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 132 with 5 attempts and 3 successes. Prob = 0.050 Actual: 0
Completed 133 with 10 attempts and 2 successes. Prob = 0.825 Actual: 0
Completed 134 with 9 attempts and 3 successes. Prob = 0.650 Actual: 1
Completed 135 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 136 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 137 with 6 attempts and 3 successes. Prob = 0.767 Actual: 1
Completed 138 with 9 attempts and 3 successes. Prob = 0.600 Actual: 1
Completed 139 with 10 attempts and 2 successes. Prob = 0.500 Actual: 1
Completed 140 with 10 attempts and 2 successes. Prob = 0.050 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 141 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 142 with 10 attempts and 2 successes. Prob = 0.500 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 143 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 144 with 10 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 145 with 10 attempts and 2 successes. Prob = 0.875 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 146 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 147 with 9 attempts and 3 successes. Prob = 0.650 Actual: 1
Completed 148 with 10 attempts and 1 successes. Prob = 0.800 Actual: 0
Completed 149 with 10 attempts and 3 successes. Prob = 0.350 Actual: 1
Completed 150 with 10 attempts and 2 successes. Prob = 0.500 Actual: 1
Completed 151 with 4 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 152 with 6 attempts and 3 successes. Prob = 0.287 Actual: 0
Completed 153 with 3 attempts and 3 successes. Prob = 0.307 Actual: 0
Completed 154 with 10 attempts and 1 successes. Prob = 0.000 Actual: 0
Completed 155 with 3 attempts and 3 successes. Prob = 0.567 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 156 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 159 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 160 with 4 attempts and 3 successes. Prob = 0.587 Actual: 0
Completed 161 with 10 attempts and 2 successes. Prob = 0.500 Actual: 0
Completed 163 with 7 attempts and 3 successes. Prob = 0.633 Actual: 0
Completed 164 with 8 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 165 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 166 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 167 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 168 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 169 with 3 attempts and 3 successes. Prob = 0.900 Actual: 0
Completed 170 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0
Completed 171 with 3 attempts and 3 successes. Prob = 0.400 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 172 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 173 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 174 with 10 attempts and 1 successes. Prob = 0.000 Actual: 0
Completed 175 with 9 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 176 with 6 attempts and 3 successes. Prob = 0.633 Actual: 0
Completed 177 with 10 attempts and 3 successes. Prob = 0.270 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 178 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 179 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 180 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 181 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 182 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 183 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 184 with 5 attempts and 3 successes. Prob = 0.850 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 185 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 186 with 5 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 187 with 8 attempts and 3 successes. Prob = 0.850 Actual: 0
Completed 188 with 3 attempts and 3 successes. Prob = 0.850 Actual: 0
Completed 189 with 3 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 190 with 3 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 191 with 10 attempts and 1 successes. Prob = 0.010 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 192 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 193 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 194 with 9 attempts and 3 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 195 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 196 with 6 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 197 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 198 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 199 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0
Completed 200 with 10 attempts and 2 successes. Prob = 0.375 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 201 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 202 with 5 attempts and 3 successes. Prob = 0.900 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 203 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 204 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 205 with 4 attempts and 3 successes. Prob = 0.540 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 206 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 207 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 208 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 209 with 9 attempts and 3 successes. Prob = 0.900 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 210 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 211 with 6 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 212 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 213 with 4 attempts and 3 successes. Prob = 0.900 Actual: 0
Completed 214 with 9 attempts and 3 successes. Prob = 0.050 Actual: 1
Completed 215 with 4 attempts and 3 successes. Prob = 0.650 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 216 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 217 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1
Completed 218 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 219 with 6 attempts and 3 successes. Prob = 0.333 Actual: 0
Completed 220 with 8 attempts and 3 successes. Prob = 0.050 Actual: 1
Completed 221 with 4 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 222 with 3 attempts and 3 successes. Prob = 0.800 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 223 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 224 with 10 attempts and 2 successes. Prob = 0.375 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 225 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 226 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 227 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 228 with 10 attempts and 2 successes. Prob = 0.825 Actual: 1
Completed 229 with 10 attempts and 3 successes. Prob = 0.250 Actual: 0
Completed 230 with 5 attempts and 3 successes. Prob = 0.867 Actual: 0
Completed 231 with 4 attempts and 3 successes. Prob = 0.550 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 232 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 233 with 10 attempts and 1 successes. Prob = 0.700 Actual: 0
Completed 234 with 10 attempts and 3 successes. Prob = 0.587 Actual: 0
Completed 235 with 4 attempts and 3 successes. Prob = 0.317 Actual: 0
Completed 236 with 10 attempts and 2 successes. Prob = 0.050 Actual: 0
Completed 237 with 3 attempts and 3 successes. Prob = 0.333 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 238 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 239 with 10 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 240 with 7 attempts and 3 successes. Prob = 0.600 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 241 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 242 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 243 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 244 with 6 attempts and 3 successes. Prob = 0.237 Actual: 0
Completed 245 with 10 attempts and 3 successes. Prob = 0.517 Actual: 0
Completed 246 with 10 attempts and 2 successes. Prob = 0.375 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 247 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 248 with 10 attempts and 2 successes. Prob = 0.950 Actual: 1
Completed 249 with 3 attempts and 3 successes. Prob = 0.650 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 250 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 251 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 252 with 7 attempts and 3 successes. Prob = 0.050 Actual: 0
Completed 253 with 3 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 254 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 255 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 256 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 257 with 6 attempts and 3 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 258 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 259 with 3 attempts and 3 successes. Prob = 0.817 Actual: 0
Completed 260 with 7 attempts and 3 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 261 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 262 with 10 attempts and 2 successes. Prob = 0.050 Actual: 0
Completed 263 with 10 attempts and 1 successes. Prob = 0.000 Actual: 0
Completed 264 with 3 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 265 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 266 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 267 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 268 with 10 attempts and 1 successes. Prob = 0.000 Actual: 0
Completed 269 with 4 attempts and 3 successes. Prob = 0.503 Actual: 0
Completed 270 with 7 attempts and 3 successes. Prob = 0.900 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 271 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 272 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 273 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 274 with 3 attempts and 3 successes. Prob = 0.650 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 275 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 276 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 277 with 6 attempts and 3 successes. Prob = 0.950 Actual: 1
Completed 278 with 7 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 279 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 280 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 281 with 10 attempts and 2 successes. Prob = 0.875 Actual: 0
Completed 282 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 283 with 6 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 284 with 10 attempts and 1 successes. Prob = 0.000 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 285 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 286 with 10 attempts and 2 successes. Prob = 0.030 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 287 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 288 with 5 attempts and 3 successes. Prob = 0.350 Actual: 1
Completed 289 with 4 attempts and 3 successes. Prob = 0.050 Actual: 0
Completed 290 with 10 attempts and 2 successes. Prob = 0.700 Actual: 0
Completed 291 with 10 attempts and 2 successes. Prob = 0.825 Actual: 0
Completed 292 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 293 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 294 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 295 with 4 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 296 with 10 attempts and 2 successes. Prob = 0.050 Actual: 0
Completed 297 with 10 attempts and 1 successes. Prob = 0.010 Actual: 0
Completed 298 with 10 attempts and 1 successes. Prob = 0.800 Actual: 0
Completed 299 with 4 attempts and 3 successes. Prob = 0.650 Actual: 1
Completed 300 with 3 attempts and 3 successes. Prob = 0.900 Actual: 0
Completed 301 with 4 attempts and 3 successes. Prob = 0.617 Actual: 0
Completed 302 with 8 attempts and 3 successes. Prob = 0.637 Actual: 0
Completed 303 with 4 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 304 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 305 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 306 with 8 attempts and 3 successes. Prob = 0.850 Actual: 0
Completed 307 with 6 attempts and 3 successes. Prob = 0.020 Actual: 0
Completed 308 with 5 attempts and 3 successes. Prob = 0.323 Actual: 0
Completed 309 with 5 attempts and 3 successes. Prob = 0.550 Actual: 0
Completed 310 with 10 attempts and 1 successes. Prob = 0.010 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 311 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 312 with 10 attempts and 2 successes. Prob = 0.875 Actual: 1
Completed 313 with 3 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 314 with 10 attempts and 2 successes. Prob = 0.925 Actual: 0
Completed 315 with 3 attempts and 3 successes. Prob = 0.050 Actual: 0
Completed 316 with 10 attempts and 3 successes. Prob = 0.050 Actual: 0
Completed 317 with 10 attempts and 3 successes. Prob = 0.900 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 318 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 319 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 320 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 321 with 4 attempts and 3 successes. Prob = 0.300 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 322 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 323 with 5 attempts and 3 successes. Prob = 0.267 Actual: 0
Completed 324 with 10 attempts and 2 successes. Prob = 0.875 Actual: 1
Completed 325 with 9 attempts and 3 successes. Prob = 0.900 Actual: 1
Completed 326 with 8 attempts and 3 successes. Prob = 0.050 Actual: 1
Completed 327 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 328 with 4 attempts and 3 successes. Prob = 0.800 Actual: 1
Completed 329 with 10 attempts and 1 successes. Prob = 0.000 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 330 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 331 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 332 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 333 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 334 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 335 with 10 attempts and 1 successes. Prob = 0.050 Actual: 0
Completed 336 with 6 attempts and 3 successes. Prob = 0.900 Actual: 1
Completed 337 with 8 attempts and 3 successes. Prob = 0.050 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 338 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 339 with 10 attempts and 1 successes. Prob = 0.800 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 340 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 341 with 10 attempts and 1 successes. Prob = 0.950 Actual: 1
Completed 342 with 9 attempts and 3 successes. Prob = 0.333 Actual: 0
Completed 343 with 6 attempts and 3 successes. Prob = 0.287 Actual: 1
Completed 344 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1
Completed 345 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 346 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 347 with 6 attempts and 3 successes. Prob = 0.583 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 348 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 349 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 350 with 8 attempts and 3 successes. Prob = 0.300 Actual: 0
Completed 351 with 10 attempts and 2 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 352 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 353 with 5 attempts and 3 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 354 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 355 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 356 with 9 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 357 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 358 with 9 attempts and 3 successes. Prob = 0.867 Actual: 0
Completed 359 with 9 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 360 with 3 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 361 with 4 attempts and 3 successes. Prob = 0.337 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 362 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 363 with 3 attempts and 3 successes. Prob = 0.900 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 364 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 365 with 6 attempts and 3 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 366 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 367 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 368 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 369 with 3 attempts and 3 successes. Prob = 0.587 Actual: 0
Completed 370 with 4 attempts and 3 successes. Prob = 0.650 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 371 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 372 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0
Completed 373 with 6 attempts and 3 successes. Prob = 0.237 Actual: 0
Completed 374 with 10 attempts and 1 successes. Prob = 0.950 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 375 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 376 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 377 with 4 attempts and 3 successes. Prob = 0.337 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 378 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 379 with 3 attempts and 3 successes. Prob = 0.533 Actual: 0
Completed 380 with 10 attempts and 1 successes. Prob = 0.800 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 381 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 382 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 383 with 9 attempts and 3 successes. Prob = 0.350 Actual: 0
Completed 384 with 3 attempts and 3 successes. Prob = 0.337 Actual: 1
Completed 385 with 3 attempts and 3 successes. Prob = 0.883 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 386 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 387 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 388 with 9 attempts and 3 successes. Prob = 0.950 Actual: 0
Completed 389 with 4 attempts and 3 successes. Prob = 0.683 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 390 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 391 with 4 attempts and 3 successes. Prob = 0.600 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 392 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 393 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 394 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 395 with 8 attempts and 3 successes. Prob = 0.350 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 396 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 397 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 398 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 399 with 3 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 400 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1
Completed 401 with 10 attempts and 2 successes. Prob = 0.050 Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 402 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 403 with 10 attempts and 0 successes. Prob = nan Actual: 1

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 404 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 405 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 406 with 8 attempts and 3 successes. Prob = 0.317 Actual: 0
Completed 407 with 10 attempts and 2 successes. Prob = 0.875 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 408 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 409 with 10 attempts and 2 successes. Prob = 0.010 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 410 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 411 with 3 attempts and 3 successes. Prob = 0.600 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 412 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 413 with 10 attempts and 2 successes. Prob = 0.900 Actual: 0
Completed 414 with 4 attempts and 3 successes. Prob = 0.933 Actual: 0
Completed 415 with 4 attempts and 3 successes. Prob = 0.337 Actual: 0
Completed 416 with 10 attempts and 2 successes. Prob = 0.050 Actual: 0
Completed 417 with 6 attempts and 3 successes. Prob = 0.650 Actual: 0
Completed 418 with 8 attempts and 3 successes. Prob = 0.850 Actual: 1
Completed 419 with 4 attempts and 3 successes. Prob = 0.537 Actual: 0
Completed 420 with 4 attempts and 3 successes. Prob = 0.900 Actual: 0
Completed 421 with 4 attempts and 3 successes. Prob = 0.617 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 422 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 423 with 10 attempts and 2 successes. Prob = 0.900 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 424 with 10 attempts and 0 successes. Prob = nan Actual: 1
Completed 425 with 4 attempts and 3 successes. Prob = 0.637 Actual: 0
Completed 426 with 10 attempts and 3 successes. Prob = 0.583 Actual: 0
Completed 427 with 8 attempts and 3 successes. Prob = 0.817 Actual: 0
Completed 428 with 10 attempts and 1 successes. Prob = 0.800 Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 429 with 10 attempts and 0 successes. Prob = nan Actual: 0

/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ck432/.conda/envs/qwen-v2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Completed 430 with 10 attempts and 0 successes. Prob = nan Actual: 0
Completed 431 with 10 attempts and 2 successes. Prob = 0.950 Actual: 0
Completed 432 with 10 attempts and 3 successes. Prob = 0.300 Actual: 0
Completed 433 with 5 attempts and 3 successes. Prob = 0.600 Actual: 0
Completed 434 with 10 attempts and 1 successes. Prob = 0.050 Actual: 1
Completed 435 with 3 attempts and 3 successes. Prob = 0.550 Actual: 0
Completed 436 with 8 attempts and 3 successes. Prob = 0.600 Actual: 0
CPU times: user 2d 3h 8min 2s, sys: 1h 12min 1s, total: 2d 4h 20min 4s
Wall time: 2h 25min 46s

In [114]:
# Calculate AUC and accuracy.
# Via https://gist.github.com/doraneko94/e24643136cfb8baf03ef8a314ab9615c
# Formula based on these articles:
# Hanley and McNeil, The meaning and use of the area under a receiver operating characteristic (ROC) curve. Radiology (1982) 43 (1) pp. 29-36.
# Fogarty, Baker and Hudson, Case Studies in the use of ROC Curve Analysis for Sensor-Based Estimates in Human Computer Interaction, Proceedings of Graphics Interface (2005) pp. 129-136.

import sklearn
from sklearn.metrics import roc_auc_score
from math import sqrt

def roc_auc_ci(y_true, y_score, positive=1):
    AUC = roc_auc_score(y_true, y_score)
    N1 = sum(y_true == positive)
    N2 = sum(y_true != positive)
    Q1 = AUC / (2 - AUC)
    Q2 = 2*AUC**2 / (1 + AUC)
    SE_AUC = sqrt((AUC*(1 - AUC) + (N1 - 1)*(Q1 - AUC**2) + (N2 - 1)*(Q2 - AUC**2)) / (N1*N2))
    lower = AUC - 1.96*SE_AUC
    upper = AUC + 1.96*SE_AUC
    if lower < 0:
        lower = 0
    if upper > 1:
        upper = 1
    return (lower, upper)

In [111]:
df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 434 entries, 0 to 436
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   profile            434 non-null    object
 1   videoURL           434 non-null    object
 2   video_posted_date  434 non-null    object
 3   is_asmr            434 non-null    int64
 4   shortcode          434 non-null    object
 5   web_url            434 non-null    object
 6   file               434 non-null    object
 7   found              434 non-null    int64
 8   response           434 non-null    object
 9   successes          434 non-null    int64
 10  attempts           434 non-null    int64
 11  pred_asmr          102 non-null    float64
dtypes: float64(1), int64(4), object(7)
memory usage: 60.2+ KB

,profile,videoURL,video_posted_date,is_asmr,shortcode,web_url,file,found,response,successes,attempts,pred_asmr
0,noniquennisa,https://www.instagram.com/reel/CnBxPwxDlG4/,2023-01-05 00:00:00,0,CnBxPwxDlG4,https://www.instagram.com/p/CnBxPwxDlG4/,noniquennisa/reels/2023-01-05 17.00.12 3008902...,1,[There is a 95% probability of rhythmic tappin...,3,3,0.950000
1,noniquennisa,https://www.instagram.com/reel/CnEWAuGjhyg/,2023-01-06 00:00:00,0,CnEWAuGjhyg,https://www.instagram.com/p/CnEWAuGjhyg/,noniquennisa/reels/2023-01-06 17.00.17 3009627...,1,"[There is rhythmic tapping in the background, ...",3,3,0.636667
2,noniquennisa,https://www.instagram.com/reel/CnG7P4cjdmz/,2023-01-07 00:00:00,0,CnG7P4cjdmz,https://www.instagram.com/p/CnG7P4cjdmz/,noniquennisa/reels/2023-01-07 17.03.18 3010353...,1,[There is a 100% chance of rhythmic tapping or...,3,4,0.800000
3,noniquennisa,https://www.instagram.com/reel/CnMEacLjnko/,2023-01-09 00:00:00,1,CnMEacLjnko,https://www.instagram.com/p/CnMEacLjnko/,noniquennisa/reels/2023-01-09 16.59.46 3011801...,1,"[There is rhythmic tapping in the background, ...",3,7,0.933333
4,noniquennisa,https://www.instagram.com/reel/CnOpQ3uDtr5/,2023-01-10 00:00:00,0,CnOpQ3uDtr5,https://www.instagram.com/p/CnOpQ3uDtr5/,noniquennisa/reels/2023-01-10 17.00.18 3012526...,1,"[There is rhythmic tapping in the background, ...",3,5,0.800000

In [137]:
#####
# Data prep
true_val = df2.is_asmr
print(f"Prevalence (original df): {np.mean(true_val):0.4f}")
predicted_val = df2.pred_asmr
analysis_df = pd.concat([true_val, predicted_val], axis = 1)
# Drop rows missing the predicted prob or the true label (hopefully none are missing the true label).
analysis_df.dropna(inplace = True)


#####
# Analysis
print(f"Prevalence (analysis df): {np.mean(analysis_df['is_asmr'].values):0.4f}")
print("Analyzed sample size:", analysis_df.shape[0])
roc_result = sklearn.metrics.roc_auc_score(analysis_df['is_asmr'], analysis_df['pred_asmr'])
auc_ci = roc_auc_ci(analysis_df['is_asmr'], analysis_df['pred_asmr'])
print(f"AUC: {roc_result:0.4f} {auc_ci[0]:0.4f}-{auc_ci[1]:0.4f}")
accuracy = np.mean((analysis_df['pred_asmr'] > 0.99).astype(int) == analysis_df['is_asmr'])
print(f"Accuracy: {accuracy:.4f}")

Prevalence (original df): 0.2488
Prevalence (analysis df): 0.2261
Analyzed sample size: 283
AUC: 0.4065 0.3304-0.4825
Accuracy: 0.7739