

conda env: mmdet-sep2023

## Init

In [19]:
from pathlib import Path
import pyprojroot
dir_proj = pyprojroot.here()
print("Project directory:", dir_proj)

import pandas as pd
import numpy as np

import torch
import mmdet
import mmcv
import platform
print("Python:", platform.python_version())
# At least 1 gpu is needed for this to run reasonably quickly.
print("PyTorch version:", torch.__version__) # 1.13.1 for DyHead
print("GPU available:", torch.cuda.is_available())
print("GPU device count:", torch.cuda.device_count())
print("CUDA version:", torch.version.cuda) # 11.7 for DyHead
print("PyTorch CUDA archs:", torch.cuda.get_arch_list())
print("mmcv version:", mmcv.__version__) # 1.6.0 for DyHead
print("mmdet version:", mmdet.__version__) # tracking dev-3.x for mmyolo conda; 2.28.2 otherwise

Project directory: /home/ck432/projects/vaping-gpt
Python: 3.8.17
PyTorch version: 1.13.1
GPU available: True
GPU device count: 4
CUDA version: 11.7
PyTorch CUDA archs: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
mmcv version: 1.6.0
mmdet version: 2.28.2

In [6]:
# Copied from score-videos.ipynb in ecig-vaping project.
model_name = "dyhead"
timestr = "20230325-193432"

dir_models = dir_proj / "models"

model_config = dir_models / str(model_name + ".py")
print("Model file:", model_config)
print("Find model:", model_config.is_file())

file_checkpoint = dir_proj / ('models/' + model_name + "-" + timestr +'.pth')
print("Checkpoint file:", file_checkpoint)
print("Find checkpoint:", file_checkpoint.is_file())

Model file: /home/ck432/projects/vaping-gpt/models/dyhead.py
Find model: True
Checkpoint file: /home/ck432/projects/vaping-gpt/models/dyhead-20230325-193432.pth
Find checkpoint: True

In [7]:
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv

# build the model from a config file and a checkpoint file
model = init_detector(model_config, str(file_checkpoint), device='cuda:0')

/home/ck432/.conda/envs/mmdet-sep2023/lib/python3.8/site-packages/mmcv/cnn/bricks/hsigmoid.py:36: UserWarning: In MMCV v1.4.4, we modified the default value of args to align with PyTorch official. Previous Implementation: Hsigmoid(x) = min(max((x + 1) / 2, 0), 1). Current Implementation: Hsigmoid(x) = min(max((x + 3) / 6, 0), 1).
  warnings.warn(
/home/ck432/projects/ecig-vaping/external/mmdetection/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '

load checkpoint from local path: /home/ck432/projects/vaping-gpt/models/dyhead-20230325-193432.pth

In [8]:
# Copied from video.ipynb
video_dir = Path("videos/GPT4_themes")
videos = list(video_dir.glob('**/*.mp4'))
print("Found", len(videos), "videos to analyze")

Found 102 videos to analyze

## Sampled analysis

In [18]:
# Based on code in video.ipynb
def analyze_videos_mmcv(videos, max_frames = 4, verbose = False):
    results = {}
    for video in videos:
        video_name = video.stem
        if (verbose):
            print(f"\nAnalyzing {video_name}")
        # Import video
        frames = load_video_mmcv(str(video), max_frames = max_frames, verbose = verbose)
        # Analyze frames
        result = analyze_frames_mmcv(frames, verbose = verbose)
        # Save results
        results[video_name] = result
    return(results)
    
def load_video_mmcv(video_path, frame_sample = 100,
                  max_frames = None, verbose = False):
    video = mmcv.VideoReader(video_path)

    # obtain basic information
    if verbose:
        print("Total frames:", len(video))
        print(video.width, video.height, video.resolution, video.fps)
    
    total_frames = len(video)

    if max_frames is None:
        frame_slice = slice(0, total_frames, frame_sample)
    else:
        step_size = int(np.ceil(total_frames / max_frames))
        frame_slice = slice(0, total_frames, step_size)

    frames = video[frame_slice]

    if verbose:
        print("Extracted frames:", len(frames))
    return frames

def analyze_frames_mmcv(frames, verbose = False):
    results = []
    for frame_i in frames:
        result = inference_detector(model, frame_i)
        results.append(result)
    # Run dyhead model
    return results

In [19]:
results = analyze_videos_mmcv(videos, verbose = True)

Analyzing fabio_fashion_3
Total frames: 406
720 1280 (720, 1280) 25.0
Extracted frames: 4

/home/ck432/projects/ecig-vaping/external/mmdetection/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(

Analyzing chamillioneyes_fashion_1
Total frames: 386
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_2
Total frames: 436
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_18
Total frames: 237
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_19
Total frames: 251
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_14
Total frames: 219
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_4
Total frames: 503
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_17
Total frames: 261
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_8
Total frames: 443
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_9
Total frames: 400
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_12
Total frames: 434
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_1
Total frames: 224
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_16
Total frames: 195
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_11
Total frames: 498
720 1280 (720, 1280) 29.0
Extracted frames: 4

Analyzing fabio_fashion_7
Total frames: 320
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_15
Total frames: 240
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_6
Total frames: 183
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_13
Total frames: 208
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_10_andpod
Total frames: 248
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_fashion_5
Total frames: 461
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_health_3
Total frames: 1730
720 720 (720, 720) 30.0
Extracted frames: 4

Analyzing drewdirps_health_2
Total frames: 1800
720 900 (720, 900) 30.0
Extracted frames: 4

Analyzing fabio_health_2_and_pod
Total frames: 1802
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_health_1
Total frames: 1671
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing chamil_health_vape
Total frames: 263
720 1280 (720, 1280) 23.976023976023978
Extracted frames: 4

Analyzing chamillioneyes_health_1
Total frames: 2127
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing edripps_health_vape
Total frames: 247
720 1280 (720, 1280) 23.976023976023978
Extracted frames: 4

Analyzing drewdirps_health_4
Total frames: 269
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing drewdirps_health_1
Total frames: 1417
720 900 (720, 900) 30.0
Extracted frames: 4

Analyzing vapes_aby_health_1_andvape
Total frames: 1290
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing vapes_aby_health_2_andvape
Total frames: 605
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing alex_health_vape
Total frames: 238
720 1280 (720, 1280) 23.976023976023978
Extracted frames: 4

Analyzing drew_health_vape
Total frames: 273
720 1280 (720, 1280) 23.976023976023978
Extracted frames: 4

Analyzing chamillioneyes_health_2
Total frames: 770
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing vapes_aby_health_vape
Total frames: 237
720 1280 (720, 1280) 23.976023976023978
Extracted frames: 4

Analyzing fabio_health_1
Total frames: 434
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing drewdirps_health_3
Total frames: 1346
720 900 (720, 900) 30.0
Extracted frames: 4

Analyzing alex_health_2
Total frames: 431
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_health_2
Total frames: 2241
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing alex_health_1
Total frames: 737
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing drewdirps_ecigs_3
Total frames: 722
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing chamillioneyes_ecgis_1
Total frames: 573
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing drewdirps_ecigs_4
Total frames: 374
720 1280 (720, 1280) 23.976023976023978
Extracted frames: 4

Analyzing edripss_ecgis_2
Total frames: 557
1080 1920 (1080, 1920) 29.0
Extracted frames: 4

Analyzing chamillioneyes_ecigs_2
Total frames: 320
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing calitrickzz_ecigs_3
Total frames: 943
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing vapes_aby_ecigs_1
Total frames: 1052
1080 1920 (1080, 1920) 26.0
Extracted frames: 4

Analyzing edripss_ecgis_1
Total frames: 690
1080 1920 (1080, 1920) 29.0
Extracted frames: 4

Analyzing vapes_aby_ecigs_2
Total frames: 779
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_ecigs_4
Total frames: 399
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_ecigs_2
Total frames: 1804
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing drewdirps_ecigs_1
Total frames: 350
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_ecigs_5
Total frames: 156
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing calitrickzz_ecigs_2
Total frames: 825
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing alex_ecigs_1
Total frames: 295
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing fabio_ecigs_1
Total frames: 430
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing drewdirps_ecigs_2
Total frames: 751
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_ecigs_1
Total frames: 520
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_ecigs_1
Total frames: 2554
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_ecigs_3
Total frames: 655
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing calitrickzz_ecigs_1
Total frames: 503
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_ecigs_2
Total frames: 1669
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_1
Total frames: 2701
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_tech_2
Total frames: 1719
1080 1920 (1080, 1920) 29.0
Extracted frames: 4

Analyzing zanxlyfe_tech_5
Total frames: 1672
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_6
Total frames: 2701
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_10
Total frames: 1087
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_4
Total frames: 1712
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_tech_4
Total frames: 1609
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_8
Total frames: 1368
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_tech_7
Total frames: 2323
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_tech_10
Total frames: 1165
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_tech_1
Total frames: 1663
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_3
Total frames: 1604
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_7
Total frames: 1509
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_2
Total frames: 2111
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_tech_5
Total frames: 1275
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_tech_6
Total frames: 1073
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing zanxlyfe_tech_9
Total frames: 896
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing arabella_tech_9
Total frames: 1406
720 1280 (720, 1280) 29.0
Extracted frames: 4

Analyzing arabella_tech_8
Total frames: 1275
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing arabella_tech_3
Total frames: 1876
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing calitrickzz_mj_16
Total frames: 657
720 1280 (720, 1280) 25.076
Extracted frames: 4

Analyzing calitrickzz_mj_11
Total frames: 186
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing calitrickzz_mj_5
Total frames: 326
1080 1920 (1080, 1920) 25.154
Extracted frames: 4

Analyzing calitrickzz_mj_3_and_golf
Total frames: 869
1080 1920 (1080, 1920) 25.058
Extracted frames: 4

Analyzing calitrickzz_mj_18
Total frames: 813
1080 1920 (1080, 1920) 25.062
Extracted frames: 4

Analyzing calitrickzz_mj_13
Total frames: 326
1080 1920 (1080, 1920) 25.154
Extracted frames: 4

Analyzing calitrickzz_mj_1
Total frames: 1065
1080 1920 (1080, 1920) 25.047
Extracted frames: 4

Analyzing calitrickzz_mj_8
Total frames: 806
1080 1920 (1080, 1920) 25.062
Extracted frames: 4

Analyzing calitrickzz_mj_9
Total frames: 505
1080 1920 (1080, 1920) 25.1
Extracted frames: 4

Analyzing calitrickzz_mj_17
Total frames: 1086
1080 1920 (1080, 1920) 30.0
Extracted frames: 4

Analyzing calitrickzz_mj_10
Total frames: 841
1080 1920 (1080, 1920) 25.06
Extracted frames: 4

Analyzing calitrickzz_mj_2
Total frames: 790
1080 1920 (1080, 1920) 25.063
Extracted frames: 4

Analyzing calitrickzz_mj_20
Total frames: 472
1080 1920 (1080, 1920) 25.107
Extracted frames: 4

Analyzing calitrickzz_mj_12
Total frames: 490
720 1280 (720, 1280) 30.0
Extracted frames: 4

Analyzing calitrickzz_mj_6
Total frames: 798
1080 1920 (1080, 1920) 25.063
Extracted frames: 4

Analyzing calitrickzz_mj_14
Total frames: 342
720 1280 (720, 1280) 25.147
Extracted frames: 4

Analyzing calitrickzz_mj_19
Total frames: 231
720 1280 (720, 1280) 25.218
Extracted frames: 4

Analyzing calitrickzz_mj_4
Total frames: 703
1080 1920 (1080, 1920) 25.071
Extracted frames: 4

Analyzing calitrickzz_mj_7
Total frames: 943
1080 1920 (1080, 1920) 25.053
Extracted frames: 4

Analyzing calitrickzz_mj_15
Total frames: 835
720 1280 (720, 1280) 25.06
Extracted frames: 4

In [20]:
len(results)

102

In [27]:
results['fabio_fashion_3']
results['fabio_ecigs_1'][1]

[array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([[7.7902830e-01, 2.4958495e+02, 1.2807602e+02, 5.8565320e+02,
         6.0633369e-02],
        [0.0000000e+00, 4.4516656e+02, 1.6996367e+02, 6.3167938e+02,
         5.6264609e-02],
        [3.2896750e+02, 8.9905157e+02, 4.5574078e+02, 1.2591453e+03,
         5.5885814e-02],
        [3.5267091e-01, 3.8996368e+01, 1.2992154e+02, 5.9218970e+02,
         5.0376859e-02],
        [4.5845648e+02, 4.4411649e+02, 7.1654413e+02, 7.5474823e+02,
         4.8534099e-02],
        [3.2571033e+02, 8.3895825e+02, 5.5125507e+02, 1.2714786e+03,
         4.4728354e-02],
        [0.0000000e+00, 3.5391766e+02, 1.6205618e+02, 6.0842877e+02,
         4.2382803e-02],
        [0.0000000e+00, 3.0163275e+02, 1.8201967e+02, 6.8926947e+02,
         3.6258545e-02]], dtype=float32),
 array([], shape=(0, 5), dtype=float32),
 array([], shape=(0, 5), dtype=float32)]

In [24]:
results.keys()

dict_keys(['fabio_fashion_3', 'chamillioneyes_fashion_1', 'fabio_fashion_2', 'fabio_fashion_18', 'fabio_fashion_19', 'fabio_fashion_14', 'fabio_fashion_4', 'fabio_fashion_17', 'fabio_fashion_8', 'fabio_fashion_9', 'fabio_fashion_12', 'fabio_fashion_1', 'fabio_fashion_16', 'fabio_fashion_11', 'fabio_fashion_7', 'fabio_fashion_15', 'fabio_fashion_6', 'fabio_fashion_13', 'fabio_fashion_10_andpod', 'fabio_fashion_5', 'fabio_health_3', 'drewdirps_health_2', 'fabio_health_2_and_pod', 'arabella_health_1', 'chamil_health_vape', 'chamillioneyes_health_1', 'edripps_health_vape', 'drewdirps_health_4', 'drewdirps_health_1', 'vapes_aby_health_1_andvape', 'vapes_aby_health_2_andvape', 'alex_health_vape', 'drew_health_vape', 'chamillioneyes_health_2', 'vapes_aby_health_vape', 'fabio_health_1', 'drewdirps_health_3', 'alex_health_2', 'arabella_health_2', 'alex_health_1', 'drewdirps_ecigs_3', 'chamillioneyes_ecgis_1', 'drewdirps_ecigs_4', 'edripss_ecgis_2', 'chamillioneyes_ecigs_2', 'calitrickzz_ecigs_3', 'vapes_aby_ecigs_1', 'edripss_ecgis_1', 'vapes_aby_ecigs_2', 'arabella_ecigs_4', 'arabella_ecigs_2', 'drewdirps_ecigs_1', 'arabella_ecigs_5', 'calitrickzz_ecigs_2', 'alex_ecigs_1', 'fabio_ecigs_1', 'drewdirps_ecigs_2', 'arabella_ecigs_1', 'zanxlyfe_ecigs_1', 'arabella_ecigs_3', 'calitrickzz_ecigs_1', 'zanxlyfe_ecigs_2', 'zanxlyfe_tech_1', 'arabella_tech_2', 'zanxlyfe_tech_5', 'zanxlyfe_tech_6', 'zanxlyfe_tech_10', 'zanxlyfe_tech_4', 'arabella_tech_4', 'zanxlyfe_tech_8', 'arabella_tech_7', 'arabella_tech_10', 'arabella_tech_1', 'zanxlyfe_tech_3', 'zanxlyfe_tech_7', 'zanxlyfe_tech_2', 'arabella_tech_5', 'arabella_tech_6', 'zanxlyfe_tech_9', 'arabella_tech_9', 'arabella_tech_8', 'arabella_tech_3', 'calitrickzz_mj_16', 'calitrickzz_mj_11', 'calitrickzz_mj_5', 'calitrickzz_mj_3_and_golf', 'calitrickzz_mj_18', 'calitrickzz_mj_13', 'calitrickzz_mj_1', 'calitrickzz_mj_8', 'calitrickzz_mj_9', 'calitrickzz_mj_17', 'calitrickzz_mj_10', 'calitrickzz_mj_2', 'calitrickzz_mj_20', 'calitrickzz_mj_12', 'calitrickzz_mj_6', 'calitrickzz_mj_14', 'calitrickzz_mj_19', 'calitrickzz_mj_4', 'calitrickzz_mj_7', 'calitrickzz_mj_15'])

In [34]:
# from compile-video-results.ipynb

import pickle

def analyze_video_detections(video_preds, video_name = "undefined"):
    # Each result contains the equivalent of the json - one element per frame, and each frame has a list of object detections for each class.

    n_frames =  len(video_preds)
    print("Frames:", n_frames)
    
    # Current class order (9):
    classes = ('box', 'e-cigarette brand name', 'e-juice', 'e-juice flavor', 'mod', 'pod', 'smoke cloud', 'synthetic nicotine label', 'warning label nicotine')
    
    # Define the columns that we want to track
    df_columns = (
                'video',
                'frame',
    ) + classes
    
    # Create a dataframe to store the frame counts for each object.
    video_df = \
        pd.DataFrame(0.,
                     index = np.arange(n_frames),
                     columns = classes)

    # Loop over each frame and extract the highest predicted prob for each class.
    for frame_i, frame in enumerate(video_preds):
                
        # These are the object detections that we want to count
        #pred_types = ('mod',
        #              'pod',
        #              'e-juice',
        #              'box',
        #              'smoke cloud')
        pred_types = classes
            
        # Loop over each prediction type that we care about and keep the highest probability for that class on this frame.
        for pred_type_i in pred_types:
            
            df_pred_col_i = list(video_df.columns).index(pred_type_i)
            
            # Find the location of this object type in the model result object.
            pred_index = classes.index(pred_type_i)

            # Count the number of predictions for this object that exceed the probability threshold for detection.
            # Extract the probability prediction for any detected objects
            frame_probs = [pred_i[4] for pred_i in frame[pred_index]]

            if len(frame_probs) > 0:
                max_prob = np.max(frame_probs)
            else:
                max_prob = 0.

            video_df.loc[frame_i, pred_type_i] = max_prob
            
    video_df['video'] = video_name
    video_df['frame'] = np.arange(n_frames)
    return(video_df)

In [37]:
video_dfs = []
for video_i, video_name in enumerate(results):
    video_result = results[video_name]
    print(f"{video_i}: {video_name}")
    video_df = analyze_video_detections(video_result, video_name)
    video_dfs.append(video_df)
        
# Combine all predictions into a single dataframe.
pred_df = pd.concat(video_dfs)

pred_df.to_parquet(dir_proj / "data/video-theme-frame-analysis.parquet")

0: fabio_fashion_3
Frames: 4
1: chamillioneyes_fashion_1
Frames: 4
2: fabio_fashion_2
Frames: 4
3: fabio_fashion_18
Frames: 4
4: fabio_fashion_19
Frames: 4
5: fabio_fashion_14
Frames: 4
6: fabio_fashion_4
Frames: 4
7: fabio_fashion_17
Frames: 4
8: fabio_fashion_8
Frames: 4
9: fabio_fashion_9
Frames: 4
10: fabio_fashion_12
Frames: 4
11: fabio_fashion_1
Frames: 4
12: fabio_fashion_16
Frames: 4
13: fabio_fashion_11
Frames: 4
14: fabio_fashion_7
Frames: 4
15: fabio_fashion_15
Frames: 4
16: fabio_fashion_6
Frames: 4
17: fabio_fashion_13
Frames: 4
18: fabio_fashion_10_andpod
Frames: 4
19: fabio_fashion_5
Frames: 4
20: fabio_health_3
Frames: 4
21: drewdirps_health_2
Frames: 4
22: fabio_health_2_and_pod
Frames: 4
23: arabella_health_1
Frames: 4
24: chamil_health_vape
Frames: 4
25: chamillioneyes_health_1
Frames: 4
26: edripps_health_vape
Frames: 4
27: drewdirps_health_4
Frames: 4
28: drewdirps_health_1
Frames: 4
29: vapes_aby_health_1_andvape
Frames: 4
30: vapes_aby_health_2_andvape
Frames: 4
31: alex_health_vape
Frames: 4
32: drew_health_vape
Frames: 4
33: chamillioneyes_health_2
Frames: 4
34: vapes_aby_health_vape
Frames: 4
35: fabio_health_1
Frames: 4
36: drewdirps_health_3
Frames: 4
37: alex_health_2
Frames: 4
38: arabella_health_2
Frames: 4
39: alex_health_1
Frames: 4
40: drewdirps_ecigs_3
Frames: 4
41: chamillioneyes_ecgis_1
Frames: 4
42: drewdirps_ecigs_4
Frames: 4
43: edripss_ecgis_2
Frames: 4
44: chamillioneyes_ecigs_2
Frames: 4
45: calitrickzz_ecigs_3
Frames: 4
46: vapes_aby_ecigs_1
Frames: 4
47: edripss_ecgis_1
Frames: 4
48: vapes_aby_ecigs_2
Frames: 4
49: arabella_ecigs_4
Frames: 4
50: arabella_ecigs_2
Frames: 4
51: drewdirps_ecigs_1
Frames: 4
52: arabella_ecigs_5
Frames: 4
53: calitrickzz_ecigs_2
Frames: 4
54: alex_ecigs_1
Frames: 4
55: fabio_ecigs_1
Frames: 4
56: drewdirps_ecigs_2
Frames: 4
57: arabella_ecigs_1
Frames: 4
58: zanxlyfe_ecigs_1
Frames: 4
59: arabella_ecigs_3
Frames: 4
60: calitrickzz_ecigs_1
Frames: 4
61: zanxlyfe_ecigs_2
Frames: 4
62: zanxlyfe_tech_1
Frames: 4
63: arabella_tech_2
Frames: 4
64: zanxlyfe_tech_5
Frames: 4
65: zanxlyfe_tech_6
Frames: 4
66: zanxlyfe_tech_10
Frames: 4
67: zanxlyfe_tech_4
Frames: 4
68: arabella_tech_4
Frames: 4
69: zanxlyfe_tech_8
Frames: 4
70: arabella_tech_7
Frames: 4
71: arabella_tech_10
Frames: 4
72: arabella_tech_1
Frames: 4
73: zanxlyfe_tech_3
Frames: 4
74: zanxlyfe_tech_7
Frames: 4
75: zanxlyfe_tech_2
Frames: 4
76: arabella_tech_5
Frames: 4
77: arabella_tech_6
Frames: 4
78: zanxlyfe_tech_9
Frames: 4
79: arabella_tech_9
Frames: 4
80: arabella_tech_8
Frames: 4
81: arabella_tech_3
Frames: 4
82: calitrickzz_mj_16
Frames: 4
83: calitrickzz_mj_11
Frames: 4
84: calitrickzz_mj_5
Frames: 4
85: calitrickzz_mj_3_and_golf
Frames: 4
86: calitrickzz_mj_18
Frames: 4
87: calitrickzz_mj_13
Frames: 4
88: calitrickzz_mj_1
Frames: 4
89: calitrickzz_mj_8
Frames: 4
90: calitrickzz_mj_9
Frames: 4
91: calitrickzz_mj_17
Frames: 4
92: calitrickzz_mj_10
Frames: 4
93: calitrickzz_mj_2
Frames: 4
94: calitrickzz_mj_20
Frames: 4
95: calitrickzz_mj_12
Frames: 4
96: calitrickzz_mj_6
Frames: 4
97: calitrickzz_mj_14
Frames: 4
98: calitrickzz_mj_19
Frames: 4
99: calitrickzz_mj_4
Frames: 4
100: calitrickzz_mj_7
Frames: 4
101: calitrickzz_mj_15
Frames: 4

In [38]:
pred_df

,box,e-cigarette brand name,e-juice,e-juice flavor,mod,pod,smoke cloud,synthetic nicotine label,warning label nicotine,video,frame
0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,fabio_fashion_3,0
1,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,fabio_fashion_3,1
2,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,fabio_fashion_3,2
3,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,fabio_fashion_3,3
0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.047046,0.0,0.000000,chamillioneyes_fashion_1,0
...,...,...,...,...,...,...,...,...,...,...,...
3,0.0,0.126527,0.049926,0.0,0.322694,0.313811,0.064886,0.0,0.043899,calitrickzz_mj_7,3
0,0.0,0.000000,0.000000,0.0,0.619724,0.050658,0.063027,0.0,0.065033,calitrickzz_mj_15,0
1,0.0,0.000000,0.000000,0.0,0.591773,0.056056,0.073923,0.0,0.050353,calitrickzz_mj_15,1
2,0.0,0.000000,0.000000,0.0,0.498510,0.090947,0.147942,0.0,0.000000,calitrickzz_mj_15,2
3,0.0,0.000000,0.000000,0.0,0.557523,0.063794,0.135307,0.0,0.000000,calitrickzz_mj_15,3

In [40]:
pred_df.to_excel("tables/dyhead-frame-predictions.xlsx")

## Full frame analysis

Pulling code from score-videos.ipynb in the ecig-vaping project.

In [9]:
videos

[PosixPath('videos/GPT4_themes/fashion/fabio_fashion_3.mp4'),
 PosixPath('videos/GPT4_themes/fashion/chamillioneyes_fashion_1.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_2.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_18.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_19.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_14.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_4.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_17.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_8.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_9.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_12.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_1.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_16.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_11.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_7.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_15.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_6.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_13.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_10_andpod.mp4'),
 PosixPath('videos/GPT4_themes/fashion/fabio_fashion_5.mp4'),
 PosixPath('videos/GPT4_themes/health/fabio_health_3.mp4'),
 PosixPath('videos/GPT4_themes/health/drewdirps_health_2.mp4'),
 PosixPath('videos/GPT4_themes/health/fabio_health_2_and_pod.mp4'),
 PosixPath('videos/GPT4_themes/health/arabella_health_1.mp4'),
 PosixPath('videos/GPT4_themes/health/chamil_health_vape.mp4'),
 PosixPath('videos/GPT4_themes/health/chamillioneyes_health_1.mp4'),
 PosixPath('videos/GPT4_themes/health/edripps_health_vape.mp4'),
 PosixPath('videos/GPT4_themes/health/drewdirps_health_4.mp4'),
 PosixPath('videos/GPT4_themes/health/drewdirps_health_1.mp4'),
 PosixPath('videos/GPT4_themes/health/vapes_aby_health_1_andvape.mp4'),
 PosixPath('videos/GPT4_themes/health/vapes_aby_health_2_andvape.mp4'),
 PosixPath('videos/GPT4_themes/health/alex_health_vape.mp4'),
 PosixPath('videos/GPT4_themes/health/drew_health_vape.mp4'),
 PosixPath('videos/GPT4_themes/health/chamillioneyes_health_2.mp4'),
 PosixPath('videos/GPT4_themes/health/vapes_aby_health_vape.mp4'),
 PosixPath('videos/GPT4_themes/health/fabio_health_1.mp4'),
 PosixPath('videos/GPT4_themes/health/drewdirps_health_3.mp4'),
 PosixPath('videos/GPT4_themes/health/alex_health_2.mp4'),
 PosixPath('videos/GPT4_themes/health/arabella_health_2.mp4'),
 PosixPath('videos/GPT4_themes/health/alex_health_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/drewdirps_ecigs_3.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/chamillioneyes_ecgis_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/drewdirps_ecigs_4.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/edripss_ecgis_2.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/chamillioneyes_ecigs_2.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/calitrickzz_ecigs_3.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/vapes_aby_ecigs_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/edripss_ecgis_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/vapes_aby_ecigs_2.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/arabella_ecigs_4.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/arabella_ecigs_2.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/drewdirps_ecigs_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/arabella_ecigs_5.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/calitrickzz_ecigs_2.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/alex_ecigs_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/fabio_ecigs_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/drewdirps_ecigs_2.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/arabella_ecigs_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/zanxlyfe_ecigs_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/arabella_ecigs_3.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/calitrickzz_ecigs_1.mp4'),
 PosixPath('videos/GPT4_themes/ecigs/zanxlyfe_ecigs_2.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_1.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_2.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_5.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_6.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_10.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_4.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_4.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_8.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_7.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_10.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_1.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_3.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_7.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_2.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_5.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_6.mp4'),
 PosixPath('videos/GPT4_themes/technology/zanxlyfe_tech_9.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_9.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_8.mp4'),
 PosixPath('videos/GPT4_themes/technology/arabella_tech_3.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_16.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_11.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_5.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_3_and_golf.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_18.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_13.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_1.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_8.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_9.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_17.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_10.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_2.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_20.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_12.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_6.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_14.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_19.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_4.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_7.mp4'),
 PosixPath('videos/GPT4_themes/marijuana/calitrickzz_mj_15.mp4')]

In [12]:
# Create video_df
video_df = pd.DataFrame({"video_path": videos})

In [14]:
video_df.describe()

                                            video_path
count                                              102
unique                                             102
top     videos/GPT4_themes/fashion/fabio_fashion_3.mp4
freq                                                 1

In [39]:
# Modified from video-evaluation.ipynb
import os

def predict_video(video_name, video_dir,
                  dir_output = pyprojroot.here() / "data/video-frame-analysis",
                  box_threshold = 0.4,
                  overwrite = False,
                  verbose = False):

    print("Analyzing", video_name)

    video_file = video_dir / video_name
    
    if not os.path.exists(video_file):
        print("Could not find video file")
        raise Exception
    
    # This will contain the .mp4 file extension.
    path_out = dir_output / str(Path(video_file).stem + "-scored.mp4")
    if verbose:
        print("Output path:", path_out)
    
    if path_out.is_file() and not overwrite:
        print("Skipping file - output already exists.")
        return
    
    # This will create an output mp4 and an output pkl (to be analyzed).
    # Default threshold is 0.3
    # Previously notebooks/video_demo-ck.py in the ecig-vaping project.
    #!python analyze-single-video.py "{video_file}" {path_model} {file_checkpoint} --out "{path_out}" --save_result --score-thr {box_threshold}
    # %run analyze-single-video.py "{video_file}" {path_model} {file_checkpoint} --out "{path_out}" --save_result --score-thr {box_threshold}
    os.system(f'python analyze-single-video.py "{video_file}" {model_config} {file_checkpoint} --out "{path_out}" --save_result --score-thr {box_threshold}')

    """!python analyze-single-video.py "{video_file}" \
        {path_model} \
        {file_checkpoint} \
        --out "{path_out}" \
        --save_result \
        --score-thr {box_threshold}"""

In [ ]:
%%time
# Takes 14.3 hours
print(f"Analyzing {video_df.shape[0]:,} videos.")
for index, row in video_df.iterrows():
    print(f"Video {index}")
    video_path = Path(row['video_path'])
    video_name = video_path.name
    video_dir = video_path.parent
    # TODO: check if video has already been analyzed.
    # Second argument is the probability threshold for showing a bounding box.
    predict_video(video_name, video_dir, #dir_output = dir_output,
                  box_threshold = 0.4, verbose = True)

## Analyze scored videos

In [45]:
# Next, translate hte code from compile-video-result.ipynb to analyze the pickle dataframes for detected objects.
# Extract all videos that have been scored
dir_output = pyprojroot.here() / "data/video-frame-analysis"
scored_videos = list(dir_output.glob("*.pkl"))
print("Scored videos found:", len(scored_videos))

Scored videos found: 102

In [46]:
import pickle

def analyze_video_pkl(video_pkl):
    video_preds = pickle.load(open(video_pkl, 'rb'))
    video_name = video_pkl.stem
    # Each pickle contains the equivalent of the json - one element per frame, and each frame has a list of object detections for each class.
    
    n_frames =  len(video_preds)
    print("Frames:", n_frames)
    
    # Current class order (9):
    classes = ('box', 'e-cigarette brand name', 'e-juice', 'e-juice flavor', 'mod', 'pod', 'smoke cloud', 'synthetic nicotine label', 'warning label nicotine')
    
    # Define the columns that we want to track
    df_columns = (
                'video',
                'frame',
    ) + classes
    
    # Create a dataframe to store the frame counts for each object.
    #video_df = \
    #    pd.DataFrame(0,
    #                 index = np.arange(n_frames),
    #                 columns = df_columns)
    
    video_df = \
        pd.DataFrame(0.,
                     index = np.arange(n_frames),
                     columns = classes)

    #video_df['frame'] = np.arange(n_frames)
    #video_df['video'] = video_name

    
    # Loop over each frame and extract the highest predicted prob for each class.
    for frame_i, frame in enumerate(video_preds):
                
        # These are the object detections that we want to count
        #pred_types = ('mod',
        #              'pod',
        #              'e-juice',
        #              'box',
        #              'smoke cloud')
        pred_types = classes
            
        # Loop over each prediction type that we care about and keep the highest probability for that class on this frame.
        for pred_type_i in pred_types:
            
            df_pred_col_i = list(video_df.columns).index(pred_type_i)
            
            # Find the location of this object type in the model result object.
            pred_index = classes.index(pred_type_i)

            # Count the number of predictions for this object that exceed the probability threshold for detection.
            # Extract the probability prediction for any detected objects
            frame_probs = [pred_i[4] for pred_i in frame[pred_index]]

            if len(frame_probs) > 0:
                max_prob = np.max(frame_probs)
            else:
                max_prob = 0.
            #print(f"Updating: {frame_i}, {pred_type_i}, {max_prob}")
            #print(len(video_df[pred_type_i]))
            #print(video_df.loc[frame_i])
            #print(video_df.loc[frame_i])

            #video_df.loc[int(frame_i), pred_type_i] = max_prob
            video_df.loc[frame_i, pred_type_i] = max_prob
            #video_df.loc[frame_i, pred_type_i] = max_prob


            #video_df.at[frame_i, df_pred_col_i] = max_prob
    video_df['video'] = video_name
    video_df['frame'] = np.arange(n_frames)
    return(video_df)

In [47]:
%%time

video_dfs = []
for video_i, video_pkl in enumerate(scored_videos):
    print(f"{video_i}: {video_pkl.stem}")
    output_file = dir_output / (video_pkl.stem + ".parquet")
    print(output_file)
    if not output_file.exists():
        video_df = analyze_video_pkl(video_pkl)
        video_df.to_parquet(output_file)
    else:
        video_df = pd.read_parquet(output_file)
    video_dfs.append(video_df)
        
# Combine all predictions into a single dataframe.
pred_df = pd.concat(video_dfs)

pred_df.to_parquet(dir_proj / "data/unlabeled-video-frames.parquet")

0: fabio_health_2_and_pod-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_health_2_and_pod-scored.parquet
Frames: 1802
1: fabio_fashion_17-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_17-scored.parquet
Frames: 261
2: arabella_tech_4-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_4-scored.parquet
Frames: 1609
3: fabio_fashion_8-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_8-scored.parquet
Frames: 443
4: zanxlyfe_tech_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_3-scored.parquet
Frames: 1604
5: arabella_tech_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_2-scored.parquet
Frames: 1719
6: alex_health_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/alex_health_2-scored.parquet
Frames: 431
7: arabella_tech_9-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_9-scored.parquet
Frames: 1406
8: fabio_fashion_14-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_14-scored.parquet
Frames: 219
9: calitrickzz_mj_5-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_5-scored.parquet
Frames: 326
10: fabio_fashion_19-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_19-scored.parquet
Frames: 251
11: calitrickzz_mj_9-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_9-scored.parquet
Frames: 505
12: fabio_fashion_12-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_12-scored.parquet
Frames: 434
13: calitrickzz_mj_10-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_10-scored.parquet
Frames: 841
14: fabio_fashion_15-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_15-scored.parquet
Frames: 240
15: drewdirps_health_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_health_1-scored.parquet
Frames: 1417
16: arabella_ecigs_4-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_ecigs_4-scored.parquet
Frames: 399
17: alex_health_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/alex_health_1-scored.parquet
Frames: 737
18: drewdirps_ecigs_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_ecigs_3-scored.parquet
Frames: 722
19: fabio_fashion_13-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_13-scored.parquet
Frames: 208
20: arabella_health_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_health_1-scored.parquet
Frames: 1671
21: calitrickzz_ecigs_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_ecigs_1-scored.parquet
Frames: 503
22: calitrickzz_mj_12-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_12-scored.parquet
Frames: 490
23: zanxlyfe_tech_6-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_6-scored.parquet
Frames: 2701
24: vapes_aby_ecigs_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/vapes_aby_ecigs_2-scored.parquet
Frames: 779
25: arabella_ecigs_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_ecigs_1-scored.parquet
Frames: 520
26: arabella_tech_7-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_7-scored.parquet
Frames: 2323
27: arabella_tech_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_3-scored.parquet
Frames: 1876
28: drewdirps_health_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_health_2-scored.parquet
Frames: 1800
29: arabella_tech_6-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_6-scored.parquet
Frames: 1073
30: fabio_fashion_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_3-scored.parquet
Frames: 406
31: calitrickzz_mj_3_and_golf-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_3_and_golf-scored.parquet
Frames: 869
32: edripss_ecgis_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/edripss_ecgis_1-scored.parquet
Frames: 690
33: drewdirps_health_4-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_health_4-scored.parquet
Frames: 269
34: zanxlyfe_tech_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_2-scored.parquet
Frames: 2111
35: arabella_tech_8-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_8-scored.parquet
Frames: 1275
36: fabio_fashion_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_2-scored.parquet
Frames: 436
37: calitrickzz_mj_19-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_19-scored.parquet
Frames: 231
38: fabio_ecigs_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_ecigs_1-scored.parquet
Frames: 430
39: alex_ecigs_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/alex_ecigs_1-scored.parquet
Frames: 295
40: vapes_aby_health_1_andvape-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/vapes_aby_health_1_andvape-scored.parquet
Frames: 1290
41: fabio_fashion_10_andpod-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_10_andpod-scored.parquet
Frames: 248
42: drew_health_vape-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drew_health_vape-scored.parquet
Frames: 273
43: calitrickzz_mj_14-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_14-scored.parquet
Frames: 342
44: zanxlyfe_ecigs_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_ecigs_2-scored.parquet
Frames: 1669
45: chamillioneyes_health_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/chamillioneyes_health_2-scored.parquet
Frames: 770
46: zanxlyfe_tech_5-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_5-scored.parquet
Frames: 1672
47: fabio_fashion_7-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_7-scored.parquet
Frames: 320
48: zanxlyfe_tech_4-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_4-scored.parquet
Frames: 1712
49: fabio_fashion_16-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_16-scored.parquet
Frames: 195
50: zanxlyfe_tech_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_1-scored.parquet
Frames: 2701
51: chamillioneyes_ecgis_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/chamillioneyes_ecgis_1-scored.parquet
Frames: 573
52: calitrickzz_mj_11-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_11-scored.parquet
Frames: 186
53: calitrickzz_mj_4-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_4-scored.parquet
Frames: 703
54: arabella_ecigs_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_ecigs_3-scored.parquet
Frames: 655
55: chamillioneyes_fashion_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/chamillioneyes_fashion_1-scored.parquet
Frames: 386
56: fabio_fashion_6-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_6-scored.parquet
Frames: 183
57: calitrickzz_ecigs_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_ecigs_2-scored.parquet
Frames: 825
58: chamillioneyes_health_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/chamillioneyes_health_1-scored.parquet
Frames: 2127
59: calitrickzz_mj_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_2-scored.parquet
Frames: 790
60: zanxlyfe_tech_9-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_9-scored.parquet
Frames: 896
61: zanxlyfe_tech_8-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_8-scored.parquet
Frames: 1368
62: vapes_aby_health_vape-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/vapes_aby_health_vape-scored.parquet
Frames: 237
63: drewdirps_ecigs_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_ecigs_2-scored.parquet
Frames: 751
64: alex_health_vape-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/alex_health_vape-scored.parquet
Frames: 238
65: fabio_fashion_11-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_11-scored.parquet
Frames: 498
66: arabella_health_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_health_2-scored.parquet
Frames: 2241
67: fabio_fashion_5-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_5-scored.parquet
Frames: 461
68: fabio_health_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_health_1-scored.parquet
Frames: 434
69: calitrickzz_mj_7-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_7-scored.parquet
Frames: 943
70: vapes_aby_ecigs_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/vapes_aby_ecigs_1-scored.parquet
Frames: 1052
71: drewdirps_ecigs_4-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_ecigs_4-scored.parquet
Frames: 374
72: drewdirps_health_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_health_3-scored.parquet
Frames: 1346
73: fabio_health_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_health_3-scored.parquet
Frames: 1730
74: calitrickzz_mj_20-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_20-scored.parquet
Frames: 472
75: calitrickzz_mj_6-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_6-scored.parquet
Frames: 798
76: fabio_fashion_18-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_18-scored.parquet
Frames: 237
77: calitrickzz_mj_16-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_16-scored.parquet
Frames: 657
78: arabella_tech_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_1-scored.parquet
Frames: 1663
79: zanxlyfe_tech_10-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_10-scored.parquet
Frames: 1087
80: drewdirps_ecigs_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/drewdirps_ecigs_1-scored.parquet
Frames: 350
81: chamillioneyes_ecigs_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/chamillioneyes_ecigs_2-scored.parquet
Frames: 320
82: zanxlyfe_tech_7-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_tech_7-scored.parquet
Frames: 1509
83: calitrickzz_mj_15-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_15-scored.parquet
Frames: 835
84: fabio_fashion_4-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_4-scored.parquet
Frames: 503
85: calitrickzz_mj_17-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_17-scored.parquet
Frames: 1086
86: vapes_aby_health_2_andvape-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/vapes_aby_health_2_andvape-scored.parquet
Frames: 605
87: calitrickzz_mj_8-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_8-scored.parquet
Frames: 806
88: edripps_health_vape-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/edripps_health_vape-scored.parquet
Frames: 247
89: arabella_ecigs_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_ecigs_2-scored.parquet
Frames: 1804
90: fabio_fashion_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_1-scored.parquet
Frames: 224
91: arabella_ecigs_5-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_ecigs_5-scored.parquet
Frames: 156
92: chamil_health_vape-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/chamil_health_vape-scored.parquet
Frames: 263
93: arabella_tech_10-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_10-scored.parquet
Frames: 1165
94: calitrickzz_ecigs_3-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_ecigs_3-scored.parquet
Frames: 943
95: zanxlyfe_ecigs_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/zanxlyfe_ecigs_1-scored.parquet
Frames: 2554
96: edripss_ecgis_2-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/edripss_ecgis_2-scored.parquet
Frames: 557
97: calitrickzz_mj_1-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_1-scored.parquet
Frames: 1065
98: calitrickzz_mj_13-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_13-scored.parquet
Frames: 326
99: fabio_fashion_9-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/fabio_fashion_9-scored.parquet
Frames: 400
100: calitrickzz_mj_18-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/calitrickzz_mj_18-scored.parquet
Frames: 813
101: arabella_tech_5-scored
/home/ck432/projects/vaping-gpt/data/video-frame-analysis/arabella_tech_5-scored.parquet
Frames: 1275

These results are then analyzed in `analyze-dyhead-predictions.Rmd`